version: '2'

services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: cont-nginx
networks: 
  default: 
    external: 
      name: net-hosting